esphome:
  name: orno_we_526
  friendly_name: orno_we_526_modbus
  project:
    name: "CyberIN.pl"
    version: "Modbus-WiFi"     

esp8266:
  board: nodemcuv2

web_server:
  port: 80

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Modbus-WiFi"

captive_portal:

status_led:
  pin:
    number: 2
    inverted: true                     

logger:
    level: DEBUG
    baud_rate: 0

uart:
  id: mod_bus
  tx_pin: 12
  rx_pin: 13
  baud_rate: 9600
  parity: NONE
  stop_bits: 1
  
modbus:
  id: modbus1

modbus_controller:
  - id: orno_we_526 # most likely similar devices will work as well
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10

sensor:

  - platform: modbus_controller
    modbus_controller_id: orno_we_526
    name: "Napięcie"
    register_type: holding
    address: 0x100
    unit_of_measurement: "V"
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.001

  - platform: modbus_controller
    modbus_controller_id: orno_we_526
    name: "Natężenie"
    register_type: holding
    address: 0x102
    unit_of_measurement: "A"
    value_type: S_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: modbus_controller
    modbus_controller_id: orno_we_526
    name: "Częstotliwość"
    register_type: holding
    address: 0x10A
    unit_of_measurement: "Hz"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
 
  - platform: modbus_controller
    modbus_controller_id: orno_we_526
    name: "Moc całkowita"
    register_type: holding
    address: 0x104
    unit_of_measurement: "W"
    value_type: S_DWORD
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: orno_we_526
    name: "Energia oddana do sieci"
    register_type: holding
    address: 0x118
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    value_type: U_DWORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01     

  - platform: modbus_controller
    modbus_controller_id: orno_we_526
    name: "Energia pobrana z sieci"
    register_type: holding
    address: 0x10E
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    value_type: U_DWORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: orno_we_526
    name: "Współczynnik mocy"
    register_type: holding
    address: 0x10B
    unit_of_measurement: "PF"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: orno_we_526
    name: "Chwilowa moc czynna pobrana"
    register_type: holding
    address: 0x176
    unit_of_measurement: "W"
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: orno_we_526
    name: "Chwilowa moc czynna oddana"
    register_type: holding
    address: 0x17A
    unit_of_measurement: "W"
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
